#ifndef BANKSIMULMYSQL_GLOBAL_H
#define BANKSIMULMYSQL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(BANKSIMULMYSQL_LIBRARY)
#  define BANKSIMULMYSQLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define BANKSIMULMYSQLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // BANKSIMULMYSQL_GLOBAL_H
